when:
  - event: push
    branch: "**"

steps:
  - name: build
    image: dhi.io/golang:1-debian-dev
    commands:
      - go install "github.com/bufbuild/buf/cmd/buf@latest"
      - buf dep update
      - go mod download
      - make build
      - make test