quarkus.application.name=tiny-file-watcher-server
quarkus.application.version=1.0.0-SNAPSHOT
quarkus.grpc.server.use-separate-server=false
# Datasource - H2 file-based database stored in the data/ folder
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/tiny-file-watcher;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=
# Hibernate ORM - automatically create/update the schema on startup
quarkus.hibernate-orm.schema-management.strategy=update

quarkus.log.category."io.github.louissantucci".level=DEBUG
quarkus.log.category."io.github.louissantucci".min-level=DEBUG